[SC-1160] Blacklist in CurveOracle
1inch/spot-price-aggregator pull request #153
Opened 2024-06-24 12:21 UTC by zZoMROT

2024-06-24 13:35 UTC, byshape requested changes

2024-06-24 13:35 UTC, byshape commented on contracts/helpers/Blacklist.sol
> +    event BlacklistAddress(address pool, bool isBlacklisted);
This form isn't in line with the naming of the rest events in the project. What do you think about `BlacklistUpdated`?

2024-06-24 13:35 UTC, byshape commented on test/Blacklist.js
> +    it('should togle record state', async function () {
```suggestion
    it('should toggle record state', async function () {
```

2024-06-24 13:46 UTC, byshape approved these changes

2024-06-25 07:47 UTC, ZumZoom approved these changes

2024-06-25 07:48 UTC, ZumZoom commented on contracts/helpers/Blacklist.sol
> +    constructor(address[] memory initialBlacklist, address owner) Ownable(owner) {
```suggestion
    constructor(address[] calldata initialBlacklist, address owner) Ownable(owner) {
```

2024-06-25 10:37 UTC, zZoMROT commented on contracts/helpers/Blacklist.sol
> +    constructor(address[] memory initialBlacklist, address owner) Ownable(owner) {
Data location must be "storage" or "memory" for constructor parameter, but "calldata" was given.

2024-06-25 18:00 UTC, merged